tools:
    shell:
        allow:
            - ls *
            - find *
            - head *
            - Get-ChildItem *
            - Select-Object Name, Mode, *
            - Where-Object { *
            - Select-Object FullName
            - Get-Content *
